# encoding: utf-8

img = Lines::Picture.create!({ image: (File.open(File.join(Rails.root, 'vendor/screenshots/octorel.png'))) })

Lines::Article.create!([
  {title: "Lines Needs You", sub_title: "", content: "We believe in the power of open source. It’s one of the best ways to push the boundaries of the web. Because LINES is still a young platform, it needs your help so it can mature and grow to its aspired size and strength. We can’t wait to see all the great things your brilliant brain and fingers will do with this project.\r\n\r\n[Fork LINES on GitHub](https://github.com/opoloo/lines)", published: true, published_at: "2015-08-05 00:00:00", gplus_url: "", featured: false, document: nil, short_hero_image: "/heroes/lines_default_01.png", teaser: "", :authors => [Lines::Author.first]},
  {title: "Customization & License", sub_title: "", content: "Find below all the important details you need to know about customizing your new blog system: modifying the stylesheets, adapting header & footer, and on.\r\n\r\nWe also made sure you get a friendly user license that gives you the freedom to do almost everything you want with this blog.\r\n\r\n#Customization\r\n\r\n##Modify CSS/SCSS\r\nAdmin viewer SCSS:\r\n\r\n`app/assets/stylesheets/admin.css.scss`\r\n\r\nDefault viewer SCSS: \r\n\r\n`app/assets/stylesheets/style.css.scss`\r\n\r\n##Header (Meta) & Footer\r\nTo change the header/meta/footer elements you need to modify\r\n\r\n`app/views/layouts/application.html.erb`\r\n\r\n#License\r\nYou may use the Lines blog template as you please. You’d make us very happy, however, if you attributed to LINES and Opoloo and kept spreading the word.\r\n\r\nWe heartily invite you to extend the features of the template, but when you do, you should fork it on GitHub, so everyone can profit from your work.\r\n\r\nYou can see the full license [here](choosealicense.com/licenses/lgpl-v3/).", published: true, published_at: "2015-08-05 00:00:00", gplus_url: "", featured: false, document: nil, short_hero_image: "/heroes/lines_default_02.png" , teaser: "", :authors => [Lines::Author.first]},
  {title: "Welcome to Your new Lines Blog", sub_title: "", content: "Thanks for downloading LINES, it’s an honor for us to know you’re using our blog framework to write and publish wonderful stuff.\r\n\r\nAs you know by now, LINES is an open source project. It’s open source for a reason—we believe that great publishing software must pass through the hands and minds of many, it must be adjustable and customizable, it must be in a state of constant development. That also means you’re in the position to make LINES serve your needs *and* to improve it for everyone. Thanks for your support.\r\n\r\nSo we’d like to heartily invite and encourage you to share your thoughts and projects with us. Your feedback is valuable and welcome.\r\n\r\nHere’s a few things that come with this Rails gem that might be interesting to know.\r\n\r\n# Technology\r\nThis blog is based on Ruby on Rails 4.0, which is all you need besides a database that supports it. We’re using a MySQL database. We’re providing as clean a code as possible, and of course we’ll maintain it and keep it up-to-date on GitHub. You’re invited to [fork](https://github.com/opoloo/lines) and improve LINES at all times.\r\n\r\n# For Developers\r\nNearly everything about this blog template can be customized to your personal needs and preferences.\r\n\r\n## Default features\r\n- Markdown editor (GitHub Flavored Markdown)\r\n- Hero graphics for posts\r\n- Upload default hero images that you want to use more frequently\r\n- Customizable generic titles & subtitles\r\n- Automatic teaser for the article overview\r\n- Four headline levels (H1–H4)\r\n- Tags for articles\r\n- Social media link\r\n- Multiple authors and author information\r\n- Add documents for download\r\n- Formating help\r\n- Direct RSS reader access\r\n- Customizable footer\r\n\r\n## Non-Features\r\n- management hassle\r\n- rights and legal bullshit\r\n- complicated settings\r\n- disco lights\r\n\r\nFor any concerns, do by all means [contact us](info@opoloo.com). We’re always interested in a good conversation.  Also, do tell us about your LINES project, we’re very curious about what you’ve built.\r\n", published: true, published_at: "2015-08-05 00:00:00", gplus_url: "", featured: false, document: nil, short_hero_image: "/heroes/lines_default_03.png", teaser: "", :authors => [Lines::Author.first]}
])
